# -*- coding: utf-8 -*-
"""seleccionVariablesIDS2018.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16XKsLv4r5RH8W5dre_nlgOtRrClKDCyj
"""

# ==========================================================
# CELDA 0 — Split train/val por host (IDS2018) · v2.3 depurada
# ==========================================================
import os, gc, re
from pathlib import Path
import numpy as np, pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

SEED = 42
np.random.seed(SEED)

# ---- Montar Drive (Colab) ----
try:
    from google.colab import drive
    if not os.path.ismount("/content/drive"):
        drive.mount('/content/drive')
except Exception:
    pass

# ---- Detectar BASE ----
CANDIDATE_BASES = [
    Path("/content/drive/MyDrive/TFG/datasets/IDS2018"),
    Path("/content/drive/MyDrive/datasets/IDS2018"),
    Path("/content/drive_cic/MyDrive/TFG/datasets/IDS2018"),
    Path("/content/drive_cic/MyDrive/datasets/IDS2018"),
]
BASE = next((b for b in CANDIDATE_BASES if b.exists()), None)
if BASE is None:
    target = "Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv"
    found = list(Path("/content/drive").rglob(target))
    if found:
        BASE = found[0].parent
assert BASE is not None, "No encuentro IDS2018 en tu Drive."
print("📁 BASE:", BASE)

RAW_FILES = [
    BASE / "Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv",
    BASE / "Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv",
    BASE / "Friday-16-02-2018_TrafficForML_CICFlowMeter.csv",
]
for f in RAW_FILES:
    assert f.exists(), f"Falta: {f.name}"
print("📄 Ficheros:", [p.name for p in RAW_FILES])

# ---- Salidas ----
OUT = BASE / "prepared"
OUT.mkdir(parents=True, exist_ok=True)
TRAIN_CSV = OUT / "train_full.csv"
VAL_CSV   = OUT / "val_full.csv"
for f in (TRAIN_CSV, VAL_CSV):
    if f.exists():
        f.unlink()

# ---- Config ----
CHUNK = 200_000
IP_REGEX = r'(\d{1,3}(?:\.\d{1,3}){3})'

# ---- Utilidades ----
def norm_key(s: str) -> str:
    s = str(s).strip().lower()
    return re.sub(r'[^a-z0-9]', '', s)

def header_map(csv_path: Path):
    df0 = pd.read_csv(csv_path, nrows=0)
    orig = list(df0.columns)
    low2orig = {norm_key(c): c for c in orig}
    return orig, low2orig

def find_col(low2orig, must_all=None, any_of=None):
    keys = list(low2orig.keys())
    if must_all:
        must_all = [norm_key(m) for m in must_all]
        for k in keys:
            if all(m in k for m in must_all):
                return low2orig[k]
    if any_of:
        any_of = [norm_key(a) for a in any_of]
        for k in keys:              # exactos
            if any(a == k for a in any_of):
                return low2orig[k]
        for k in keys:              # contiene
            if any(a in k for a in any_of):
                return low2orig[k]
    return None

def labels_to01(s):
    s = pd.Series(s, dtype=str).str.strip().str.lower()
    return np.where((s=="benign")|(s=="normal"), 0, 1).astype(np.int8)

def first_ip(series):
    s = pd.Series(series, dtype=str)
    return s.str.extract(IP_REGEX, expand=False)

def choose_host_columns(low2orig):
    col_src = find_col(low2orig, any_of=[
        "src ip","source ip","src_ip","source_ip","src addr","source addr",
        "srcaddress","srcaddr","source address"
    ])
    col_dst = find_col(low2orig, any_of=[
        "dst ip","destination ip","dst_ip","destination_ip","dst addr",
        "destination addr","dstaddress","dstaddr","destination address"
    ])
    col_flow = find_col(low2orig, must_all=["flow","id"])
    return col_src, col_dst, col_flow

def get_host_series(chunk, col_src, col_dst, col_flow):
    if col_src is not None and col_src in chunk.columns:
        ip = first_ip(chunk[col_src]);
        if ip.notna().any(): return ip
    if col_dst is not None and col_dst in chunk.columns:
        ip = first_ip(chunk[col_dst]);
        if ip.notna().any(): return ip
    if col_flow is not None and col_flow in chunk.columns:
        ip = first_ip(chunk[col_flow]);
        if ip.notna().any(): return ip
    # último recurso: columnas con 'ip/addr/address'
    for c in chunk.columns:
        nk = norm_key(c)
        if ("ip" in nk) or ("addr" in nk) or ("address" in nk):
            ip = first_ip(chunk[c])
            if ip.notna().any(): return ip
    return pd.Series([None]*len(chunk))

# ---- PASO 1: contar por host (stream) ----
print("🔎 Recuento por host (stream)…")
host_counts = {}
total_rows = 0

for csv_path in RAW_FILES:
    _, low2orig = header_map(csv_path)
    col_label = find_col(low2orig, any_of=["label","class","attack_cat"])
    assert col_label is not None, f"No encuentro columna 'Label' en {csv_path.name}"
    col_src, col_dst, col_flow = choose_host_columns(low2orig)

    usecols = [c for c in [col_label, col_src, col_dst, col_flow] if c is not None] or [col_label]

    for chunk in pd.read_csv(csv_path, usecols=usecols, chunksize=CHUNK, dtype=str, engine="c"):
        total_rows += len(chunk)
        y = labels_to01(chunk[col_label])
        if any([col_src, col_dst, col_flow]):
            host = get_host_series(chunk, col_src, col_dst, col_flow)
            mask = host.notna()
            if mask.any():
                df_aux = pd.DataFrame({"host": host[mask].values, "y": y[mask.values]})
                gb = df_aux.groupby("host")["y"]
                attacks = gb.sum(); totals = gb.count(); benigns = totals - attacks
                for h in attacks.index:
                    b = int(benigns.loc[h]); a = int(attacks.loc[h])
                    if h in host_counts:
                        host_counts[h][0] += b; host_counts[h][1] += a
                    else:
                        host_counts[h] = [b, a]
    gc.collect()

print(f"✅ Hosts: {len(host_counts)} | filas: {total_rows:,}")

# ---- Estratificar hosts (B/M/A por % ataque) ----
hosts = np.array(list(host_counts.keys()))
counts = np.array(list(host_counts.values()), dtype=np.int64) if host_counts else np.zeros((0,2), dtype=np.int64)
if len(hosts) > 0:
    benign, attack = counts[:,0], counts[:,1]
    totals = benign + attack
    frac_attack = np.divide(attack, np.maximum(totals,1), where=totals>0)
    cats = np.full_like(frac_attack, "M", dtype=object)
    cats[frac_attack <= 0.2] = "B"; cats[frac_attack >= 0.8] = "A"
    sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=SEED)
    idx_tr, idx_va = next(sss.split(hosts.reshape(-1,1), cats))
    TRAIN_HOSTS, VAL_HOSTS = set(hosts[idx_tr]), set(hosts[idx_va])
else:
    TRAIN_HOSTS, VAL_HOSTS = set(), set()
print(f"📑 Hosts → train:{len(TRAIN_HOSTS)} | val:{len(VAL_HOSTS)}")

# ---- PASO 2: volcado por chunks (con cabeceras independientes) ----
print("💾 Escribiendo train_full.csv y val_full.csv…")
header_written_train = False
header_written_val   = False
n_train = n_val = 0

for csv_path in RAW_FILES:
    _, low2orig = header_map(csv_path)
    col_label = find_col(low2orig, any_of=["label","class","attack_cat"])
    col_src, col_dst, col_flow = choose_host_columns(low2orig)

    for chunk in pd.read_csv(csv_path, chunksize=CHUNK, engine="c"):
        # serie de host (puede no existir en algunos ficheros)
        host = get_host_series(chunk, col_src, col_dst, col_flow)

        if host.isna().all():
            # fallback: split estratificado por filas usando y
            y = labels_to01(chunk[col_label])
            sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=SEED)
            idx_tr, idx_va = next(sss.split(np.zeros((len(y),1)), y))
            mask_tr = pd.Series(False, index=chunk.index); mask_tr.iloc[idx_tr] = True
            mask_va = ~mask_tr
        else:
            is_train = host.isin(TRAIN_HOSTS)
            is_val   = host.isin(VAL_HOSTS)
            unknown  = ~(is_train | is_val)
            mask_tr = is_train | unknown   # desconocidos → train
            mask_va = is_val

        tr_part = chunk.loc[mask_tr]
        va_part = chunk.loc[mask_va]

        if len(tr_part):
            tr_part.to_csv(
                TRAIN_CSV, index=False, mode="a",
                header=(not header_written_train)
            )
            n_train += len(tr_part)
            header_written_train = True

        if len(va_part):
            va_part.to_csv(
                VAL_CSV, index=False, mode="a",
                header=(not header_written_val)
            )
            n_val += len(va_part)
            header_written_val = True

    gc.collect()

print(f"✅ Terminado. Filas → train: {n_train:,} | val: {n_val:,}")
print("Archivos:")
print(" -", TRAIN_CSV)
print(" -", VAL_CSV)

# ============================================
# CELDA 0.5 — ¿Cuántas columnas tiene IDS2018?
# ============================================
from pathlib import Path
import pandas as pd

def ncols(path: Path) -> int:
    return len(pd.read_csv(path, nrows=0).columns)

def header(path: Path):
    return list(pd.read_csv(path, nrows=0).columns)

print("RAW (CSV originales):")
raw_headers = []
for p in RAW_FILES:
    c = ncols(p)
    print(f" - {p.name}: {c} columnas")
    raw_headers.append((p.name, header(p)))

# ¿coinciden los encabezados entre días?
same = all(raw_headers[0][1] == h for _, h in raw_headers[1:])
if not same:
    print("\n⚠️ Los encabezados NO son idénticos entre días.")
    base = set(raw_headers[0][1])
    for name, h in raw_headers[1:]:
        extra = set(h) - base
        miss  = base - set(h)
        if extra:
            print(f"   · {name} tiene columnas extra: {sorted(list(extra))[:8]}{' …' if len(extra)>8 else ''}")
        if miss:
            print(f"   · {name} le faltan: {sorted(list(miss))[:8]}{' …' if len(miss)>8 else ''}")
else:
    print("✅ Los encabezados de los 3 días son idénticos.")

# PREPARED (si existen)
for p in [TRAIN_CSV, VAL_CSV]:
    if p.exists():
        print(f"\n{p.name}: {ncols(p)} columnas")

# ==========================================================
# CELDA 1 — Carga robusta train/val + label binaria + limpieza
# ==========================================================
import json, gc
from pathlib import Path
import numpy as np, pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

# --- Rutas esperadas desde la Celda 0 ---
assert 'OUT' in globals(), "Ejecuta antes la CELDA 0 para crear prepared/train_full.csv y val_full.csv."
TRAIN_CSV = (OUT / "train_full.csv")
VAL_CSV   = (OUT / "val_full.csv")
assert TRAIN_CSV.exists() and VAL_CSV.exists(), "Faltan prepared/train_full.csv y/o val_full.csv."

# --- Carpeta de artefactos ---
if 'MODEL_DIR' not in globals():
    MODEL_DIR = Path("/content/drive/MyDrive/TFG/modelo_guardado_CIC2018")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

SEED = 42
np.random.seed(SEED)

# ----------------- Helpers -----------------
def header_lower_map(csv_path: Path):
    """Devuelve (cols_originales, dict lower->original) leyendo solo cabecera."""
    df0 = pd.read_csv(csv_path, nrows=0)
    orig = list(df0.columns)
    low2orig = {str(c).strip().lower(): c for c in orig}
    return orig, low2orig

def is_drop(col_lower: str) -> bool:
    """Columnas no utilizables como features (ids, tiempos, IPs, etiquetas)."""
    DROP_EXACT = {
        'label','src ip','dst ip','srcip','dstip',
        'flow id','flow_id','flow id.1',
        'timestamp','timestamp_','stime'
    }
    if col_lower in DROP_EXACT:
        return True
    if ('flow' in col_lower and 'id' in col_lower):
        return True
    if 'time' in col_lower and ('stamp' in col_lower or col_lower.endswith('time')):
        return True
    return False

def coerce_numeric(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    out = df.copy()
    for c in cols:
        if out[c].dtype.kind not in "iufc":
            out[c] = pd.to_numeric(out[c], errors='coerce')
    return out

def label_to01(s):
    s = pd.Series(s, dtype=str).str.strip().str.lower()
    return np.where((s=="benign")|(s=="normal"), 0, 1).astype(np.int8)

# ----------------- 1) Columnas canónicas desde TRAIN -----------------
train_orig, train_l2o = header_lower_map(TRAIN_CSV)
cols_lower = [str(c).strip().lower() for c in train_orig]
want_lower = ['label'] + [c for c in cols_lower if not is_drop(c)]
usecols_train = [train_l2o[c] for c in want_lower if c in train_l2o]

# ----------------- 2) Leer TRAIN y VAL de forma robusta -----------------
df_train = pd.read_csv(TRAIN_CSV, usecols=usecols_train, engine="c", low_memory=False)
df_train.columns = [str(c).strip().lower() for c in df_train.columns]

try:
    val_orig, val_l2o = header_lower_map(VAL_CSV)
    usecols_val = [val_l2o[c] for c in want_lower if c in val_l2o]
    if len(usecols_val) == 0:
        raise KeyError("VAL sin cabecera utilizable")
    df_val = pd.read_csv(VAL_CSV, usecols=usecols_val, engine="c", low_memory=False)
    df_val.columns = [str(c).strip().lower() for c in df_val.columns]
except Exception:
    # Fallback: VAL sin cabecera → mapear columnas como en TRAIN
    tmp = pd.read_csv(VAL_CSV, header=None, engine="c", low_memory=False)
    if tmp.shape[1] != len(train_orig):
        # Alinear número de columnas al de TRAIN
        if tmp.shape[1] > len(train_orig):
            tmp = tmp.iloc[:, :len(train_orig)]
        else:
            for i in range(len(train_orig) - tmp.shape[1]):
                tmp[f"_pad_{i}"] = np.nan
    tmp.columns = train_orig
    df_val = tmp[usecols_train].copy()
    df_val.columns = [str(c).strip().lower() for c in df_val.columns]
    del tmp; gc.collect()

print("📥 Cargado:", "train", df_train.shape, "| val", df_val.shape)

# ----------------- 3) Label binaria + lista de features -----------------
assert 'label' in df_train.columns, "No se encuentra 'label' en train."
df_train['label'] = label_to01(df_train['label'])
df_val  ['label'] = label_to01(df_val  ['label'])

y_train_full = df_train['label'].astype(int).to_numpy()
y_val        = df_val['label'].astype(int).to_numpy()
feature_cols = [c for c in df_train.columns if c != 'label']
print(f"🔢 Candidatas iniciales: {len(feature_cols)}")

# ----------------- 4) Muestreo estratificado opcional (RAM/tiempo) -----------------
MAX_TRAIN_ROWS = 600_000  # ajusta si necesitas más/menos
if len(df_train) > MAX_TRAIN_ROWS:
    frac = MAX_TRAIN_ROWS / len(df_train)
    sss = StratifiedShuffleSplit(n_splits=1, test_size=1-frac, random_state=SEED)
    idx_tr, _ = next(sss.split(np.zeros((len(y_train_full), 1)), y_train_full))
    df_train = df_train.iloc[idx_tr].reset_index(drop=True)
    y_train  = df_train['label'].astype(int).to_numpy()
else:
    y_train  = y_train_full

# ----------------- 5) Casting numérico + limpieza -----------------
df_train_num = coerce_numeric(df_train, feature_cols)
df_val_num   = coerce_numeric(df_val,   feature_cols)

# Inf → NaN
df_train_num = df_train_num.replace([np.inf, -np.inf], np.nan)
df_val_num   = df_val_num.replace([np.inf, -np.inf], np.nan)

# Quitar columnas totalmente NaN en train
all_nan = df_train_num[feature_cols].columns[df_train_num[feature_cols].isna().all()].tolist()
if all_nan:
    feature_cols = [c for c in feature_cols if c not in all_nan]
    df_train_num = df_train_num.drop(columns=all_nan)
    df_val_num   = df_val_num.drop(columns=all_nan, errors='ignore')

# Imputación con mediana (calculada en train)
med = df_train_num[feature_cols].median(numeric_only=True)
df_train_num[feature_cols] = df_train_num[feature_cols].fillna(med)
df_val_num  [feature_cols] = df_val_num  [feature_cols].fillna(med.reindex(df_val_num[feature_cols].columns))

# Eliminar columnas constantes
stds = df_train_num[feature_cols].std(axis=0)
const_cols = stds[stds <= 0].index.tolist()
if const_cols:
    feature_cols = [c for c in feature_cols if c not in const_cols]
    df_train_num = df_train_num.drop(columns=const_cols)
    df_val_num   = df_val_num.drop(columns=const_cols, errors='ignore')

# ----------------- 6) Construcción de matrices -----------------
X_train_raw = df_train_num[feature_cols].astype(np.float32).to_numpy(copy=False)
X_val_raw   = df_val_num  [feature_cols].astype(np.float32).to_numpy(copy=False)
y_train     = df_train_num['label'].astype(int).to_numpy()
y_val       = df_val_num  ['label'].astype(int).to_numpy()
FEATURES_RAW = feature_cols

print("✅ Limpieza OK | X_train_raw:", X_train_raw.shape, "| X_val_raw:", X_val_raw.shape, "| features:", len(FEATURES_RAW))

# ----------------- 7) Guardar trazabilidad -----------------
with open(MODEL_DIR / "features_raw_IDS2018.json", "w") as f:
    json.dump(FEATURES_RAW, f, indent=2)

gc.collect()
print("💾 Guardado: features_raw_IDS2018.json →", MODEL_DIR)
print("🏁 CELDA 1 lista — datos preparados para filtros y Ridge/Lasso.")

# ==========================================================
# CELDA 2 — Filtro de varianza baja + alta correlación (inteligente)
# ==========================================================
import numpy as np, pandas as pd, json, gc
from pathlib import Path

# Requiere: X_train_raw, X_val_raw, y_train, y_val, FEATURES_RAW, MODEL_DIR (de la Celda 1)
for v in ["X_train_raw","X_val_raw","y_train","y_val","FEATURES_RAW","MODEL_DIR"]:
    assert v in globals(), f"Ejecuta antes la Celda 1: falta {v}"

THRESH_VAR  = 1e-8     # casi-constantes
THRESH_CORR = 0.90     # redundancia

Xtr = X_train_raw.astype(np.float32, copy=False)
Xva = X_val_raw.astype(np.float32, copy=False)
feat = FEATURES_RAW[:]

# ---------- 1) Filtro de varianza baja ----------
var_tr = np.nanvar(Xtr, axis=0)
mask_var = var_tr > THRESH_VAR
dropped_var = [f for f, keep in zip(feat, mask_var) if not keep]
if dropped_var:
    print(f"🧽 Varianza baja → drop {len(dropped_var)} cols:", dropped_var[:10], ("..." if len(dropped_var)>10 else ""))

Xtr = Xtr[:, mask_var]
Xva = Xva[:, mask_var]
feat = [f for f, keep in zip(feat, mask_var) if keep]

# ---------- 2) Eliminar alta correlación guiado por |corr con y| ----------
def corr_with_y(X: np.ndarray, y: np.ndarray) -> np.ndarray:
    # point-biserial == Pearson entre X y y (binaria) tras z-score
    yc = y.astype(np.float32)
    yc = (yc - yc.mean()) / (yc.std() + 1e-12)
    Xc = (X - X.mean(axis=0)) / (X.std(axis=0) + 1e-12)
    return (Xc * yc[:, None]).mean(axis=0)

def drop_high_corr_features(X: np.ndarray, features: list, y: np.ndarray, thr: float):
    n = X.shape[1]
    if n <= 1:
        return np.ones(n, dtype=bool), [], np.zeros(n, dtype=np.float32)
    # z-score para matriz de correlación
    Xc = (X - X.mean(axis=0)) / (X.std(axis=0) + 1e-12)
    corr = (Xc.T @ Xc) / (Xc.shape[0])  # Pearson
    cy = corr_with_y(X, y)              # importancia univariada

    keep = np.ones(n, dtype=bool)
    dropped = []  # (dropped, kept, r)

    for i in range(n):
        if not keep[i]:
            continue
        high = np.where(np.abs(corr[i, i+1:]) >= thr)[0] + (i+1)
        for j in high:
            if not keep[j]:
                continue
            # conservar la de mayor |corr con y|
            if abs(cy[i]) >= abs(cy[j]):
                keep[j] = False
                dropped.append((features[j], features[i], float(corr[i, j])))
            else:
                keep[i] = False
                dropped.append((features[i], features[j], float(corr[i, j])))
                break  # i ya descartada, pasa al siguiente i
    return keep, dropped, cy

keep_corr, dropped_pairs, corr_y = drop_high_corr_features(Xtr, feat, y_train, THRESH_CORR)

Xtr_f = Xtr[:, keep_corr]
Xva_f = Xva[:, keep_corr]
feat_f = [f for f, k in zip(feat, keep_corr) if k]

print(f"🔗 Alta correlación (|r|≥{THRESH_CORR}) → drop {np.count_nonzero(~keep_corr)} cols")
if dropped_pairs[:5]:
    print("   Ejemplos de pares descartados (drop, keep, r):")
    for d, k, r in dropped_pairs[:5]:
        print(f"   - {d}  vs  {k}  | r={r:.3f}")

# ---------- 3) Resumen + guardado de trazabilidad ----------
print("✅ Filtros listos")
print("   X_train_filt:", Xtr_f.shape, "  X_val_filt:", Xva_f.shape)
print("   Features para Ridge/Lasso:", len(feat_f))

MODEL_DIR.mkdir(parents=True, exist_ok=True)

# stats después del filtro de varianza (para las que quedaron)
pd.DataFrame({
    "feature": feat,
    "var_train": np.nanvar(Xtr, axis=0),
    "corr_y": corr_y
}).to_csv(MODEL_DIR / "features_stats_after_var_IDS2018.csv", index=False)

pd.DataFrame(dropped_pairs, columns=["dropped","kept","pair_corr"])\
  .to_csv(MODEL_DIR / "dropped_pairs_highcorr_IDS2018.csv", index=False)

with open(MODEL_DIR / "features_after_filters_IDS2018.json", "w") as f:
    json.dump(feat_f, f, indent=2)

# ---------- 4) Dejar objetos en RAM para Celda 3 ----------
X_train_filt = Xtr_f.astype(np.float32, copy=False)
X_val_filt   = Xva_f.astype(np.float32, copy=False)
FEATURES_FILT = feat_f

gc.collect()

# ==========================================================
# CELDA 2b — Matriz de correlación (RAW vs FILT) + top pares
# ==========================================================
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from pathlib import Path

assert all(v in globals() for v in ["X_train_raw","FEATURES_RAW","X_train_filt","FEATURES_FILT","MODEL_DIR"])

THR = 0.90  # umbral de redundancia

def corr_mat(X: np.ndarray) -> np.ndarray:
    X = X.astype(np.float64, copy=False)
    Z = (X - X.mean(axis=0)) / (X.std(axis=0) + 1e-12)
    C = (Z.T @ Z) / Z.shape[0]
    return np.clip(C, -1.0, 1.0)

def count_pairs(C: np.ndarray, thr: float) -> int:
    n = C.shape[0]
    iu = np.triu_indices(n, k=1)
    return int((np.abs(C[iu]) >= thr).sum())

def top_pairs(C: np.ndarray, labels: list, k=10):
    n = C.shape[0]
    iu = np.triu_indices(n, k=1)
    vals = np.abs(C[iu])
    idx = np.argsort(-vals)[:k]
    pairs = []
    for t in idx:
        i, j = iu[0][t], iu[1][t]
        pairs.append((labels[i], labels[j], float(C[i, j])))
    return pairs

def save_heatmap(C: np.ndarray, labels: list, title: str, out_png: Path, tick_step=3):
    plt.figure(figsize=(10, 9))
    plt.imshow(C, vmin=-1, vmax=1, cmap="coolwarm", interpolation="nearest")
    plt.colorbar(label="r (Pearson)")
    n = len(labels)
    ticks = np.arange(0, n, max(1, tick_step))
    plt.xticks(ticks, [labels[i] for i in ticks], rotation=90, fontsize=7)
    plt.yticks(ticks, [labels[i] for i in ticks], fontsize=7)
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_png, dpi=150)
    plt.show()

# --- RAW ---
C_raw = corr_mat(X_train_raw); n_pairs_raw = count_pairs(C_raw, THR)
save_heatmap(C_raw, FEATURES_RAW, f"Correlación RAW (|r|≥{THR}) — IDS2018",
             MODEL_DIR / "corr_heatmap_RAW_IDS2018.png")
pd.DataFrame(C_raw, index=FEATURES_RAW, columns=FEATURES_RAW)\
  .to_csv(MODEL_DIR / "corr_matrix_RAW_IDS2018.csv", index=True)

# --- FILT ---
C_filt = corr_mat(X_train_filt); n_pairs_filt = count_pairs(C_filt, THR)
save_heatmap(C_filt, FEATURES_FILT, f"Correlación FILT (|r|≥{THR}) — IDS2018",
             MODEL_DIR / "corr_heatmap_FILT_IDS2018.png")
pd.DataFrame(C_filt, index=FEATURES_FILT, columns=FEATURES_FILT)\
  .to_csv(MODEL_DIR / "corr_matrix_FILT_IDS2018.csv", index=True)

# --- Top pares correlacionados (después del filtro) ---
top10 = top_pairs(C_filt, FEATURES_FILT, k=10)
print(f"🔗 Pairs |r|≥{THR} — RAW : {n_pairs_raw}")
print(f"🔗 Pairs |r|≥{THR} — FILT: {n_pairs_filt}")
print("🏷️ Top 10 pares (FILT) por |r|:")
for a,b,r in top10:
    print(f"   - {a} ↔ {b}  | r={r:.3f}")

print("💾 Guardados en:", MODEL_DIR)
print("   - corr_heatmap_RAW_IDS2018.png / corr_matrix_RAW_IDS2018.csv")
print("   - corr_heatmap_FILT_IDS2018.png / corr_matrix_FILT_IDS2018.csv")

# ==========================================================
# CELDA 3 — Ridge + Lasso y selección final (TOP_K)
# ==========================================================
import numpy as np, pandas as pd, json, gc, warnings
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.linear_model import RidgeCV, LassoCV

# Requiere: X_train_filt, X_val_filt, y_train, y_val, FEATURES_FILT, MODEL_DIR
for v in ["X_train_filt","X_val_filt","y_train","y_val","FEATURES_FILT","MODEL_DIR"]:
    assert v in globals(), f"Falta {v}. Ejecuta Celdas 1 y 2."

SEED = 42
np.random.seed(SEED)

# ---------- 1) Muestreo para modelos lineales (control RAM/tiempo) ----------
SAMPLE_FOR_LINEAR = 300_000   # puedes subir/bajar si quieres
if X_train_filt.shape[0] > SAMPLE_FOR_LINEAR:
    frac = SAMPLE_FOR_LINEAR / X_train_filt.shape[0]
    print(f"✂️ Muestreando para lineales ~{SAMPLE_FOR_LINEAR:,} ({frac:.2%})…")
    sss = StratifiedShuffleSplit(n_splits=1, test_size=1-frac, random_state=SEED)
    idx_tr, _ = next(sss.split(np.zeros((y_train.shape[0],1)), y_train))
    X_lin = X_train_filt[idx_tr]
    y_lin = y_train[idx_tr]
else:
    X_lin = X_train_filt
    y_lin = y_train

# Convertir a float64 para estabilidad
X_lin64 = X_lin.astype(np.float64, copy=False)

# ---------- 2) Estandarizar ----------
scaler = StandardScaler(with_mean=True, with_std=True)
X_lin_std = scaler.fit_transform(X_lin64)

# ---------- 3) RIDGE (ranking por magnitud de coeficientes) ----------
ALPHAS_RIDGE = np.logspace(-3, 3, 13)  # 0.001..1000
ridge = RidgeCV(alphas=ALPHAS_RIDGE, cv=3, scoring="neg_mean_squared_error")
ridge.fit(X_lin_std, y_lin.astype(np.float64))
coef_ridge = ridge.coef_
abs_ridge = np.abs(coef_ridge)

ridge_rank_idx   = np.argsort(-abs_ridge)  # descendente
ridge_rank_feats = [FEATURES_FILT[i] for i in ridge_rank_idx]
ridge_rank_vals  = abs_ridge[ridge_rank_idx]

print(f"🏁 RidgeCV alpha*: {ridge.alpha_}")

# ---------- 4) LASSO (sparsity) ----------
warnings.filterwarnings("ignore", category=UserWarning)
lasso = LassoCV(
    eps=1e-3,
    n_alphas=40,
    cv=3,
    max_iter=8000,   # un poco más alto por si tarda en converger
    n_jobs=-1,
    random_state=SEED,
)
lasso.fit(X_lin_std, y_lin.astype(np.float64))
coef_lasso = lasso.coef_
selected_mask = np.abs(coef_lasso) > 1e-8
lasso_selected = [f for f, m in zip(FEATURES_FILT, selected_mask) if m]

print(f"🏁 LassoCV alpha*: {lasso.alpha_}")
print(f"✔️ Lasso seleccionó {len(lasso_selected)} features")

# ---------- 5) Ensamblar set final ----------
TOP_K = 27  # como en UNSW (ajustable)
final_feats = list(lasso_selected)

if len(final_feats) > TOP_K:
    # ordenar las de Lasso usando ranking de Ridge
    order_map = {f:i for i,f in enumerate(ridge_rank_feats)}
    final_feats = sorted(final_feats, key=lambda f: order_map.get(f, 10**9))[:TOP_K]
elif len(final_feats) < TOP_K:
    for f in ridge_rank_feats:
        if f not in final_feats:
            final_feats.append(f)
            if len(final_feats) == TOP_K:
                break

print(f"🎯 Features finales (TOP_K={TOP_K}): {len(final_feats)}")
print("   Top 10 finales:", final_feats[:10])

# ---------- 6) Guardar artefactos ----------
MODEL_DIR.mkdir(parents=True, exist_ok=True)

# tabla con coeficientes
pd.DataFrame({
    "feature": FEATURES_FILT,
    "ridge_abs_coef": np.abs(coef_ridge),
    "lasso_coef": coef_lasso,
    "selected_by_lasso": selected_mask.astype(int),
}).to_csv(MODEL_DIR / "features_ridge_lasso_table_IDS2018.csv", index=False)

# ranking ridge completo
pd.DataFrame({
    "feature": ridge_rank_feats,
    "abs_coef": ridge_rank_vals
}).to_csv(MODEL_DIR / "features_rank_ridge_IDS2018.csv", index=False)

# listas clave
with open(MODEL_DIR / "features_selected_lasso_IDS2018.json", "w") as f:
    json.dump(lasso_selected, f, indent=2)

with open(MODEL_DIR / "features_final_IDS2018.json", "w") as f:
    json.dump(final_feats, f, indent=2)

# dejar en RAM por si quieres seguir
FEATURES_FINAL = final_feats
RIDGE_COEF = coef_ridge
LASSO_COEF = coef_lasso

print("💾 Guardados en:", MODEL_DIR)
print("   - features_ridge_lasso_table_IDS2018.csv")
print("   - features_rank_ridge_IDS2018.csv")
print("   - features_selected_lasso_IDS2018.json")
print("   - features_final_IDS2018.json")

gc.collect()

# ==========================================================
# CELDA 3b — Mostrar variables definitivas (TopK y Consenso)
# ==========================================================
import json, pandas as pd
from pathlib import Path

assert 'MODEL_DIR' in globals(), "Ejecuta antes las celdas previas."

p_topk = MODEL_DIR / "features_final_IDS2018.json"
p_cons = MODEL_DIR / "features_final_consensus_IDS2018.json"
assert p_topk.exists(), "Falta features_final_IDS2018.json (Celda 3)."
assert p_cons.exists(), "Falta features_final_consensus_IDS2018.json (Celda 4)."

feat_topk = json.loads(p_topk.read_text())
feat_cons = json.loads(p_cons.read_text())

print(f"🧱 TopK (Celda 3): {len(feat_topk)} features")
for i, f in enumerate(feat_topk, 1):
    print(f"{i:2d}. {f}")

print("\n🧱 Consenso (Celda 4): {0} features".format(len(feat_cons)))
for i, f in enumerate(feat_cons, 1):
    print(f"{i:2d}. {f}")

# Resumen rápido
topk_set, cons_set = set(feat_topk), set(feat_cons)
print("\n📌 Intersección:", len(topk_set & cons_set))
print("📌 Solo en TopK :", len(topk_set - cons_set))
print("📌 Solo en Cons.:", len(cons_set - topk_set))
print("📌 Jaccard      :", round(len(topk_set & cons_set)/len(topk_set | cons_set), 3))

# ==========================================================
# CELDA 3c — Tabla consolidada de importancia (TopK/Consenso)
# ==========================================================
import json, pandas as pd, numpy as np
from pathlib import Path

# Cargas
p_topk = MODEL_DIR / "features_final_IDS2018.json"
p_cons = MODEL_DIR / "features_final_consensus_IDS2018.json"
p_rl   = MODEL_DIR / "features_ridge_lasso_table_IDS2018.csv"  # Celda 3
p_stab = MODEL_DIR / "features_stability_IDS2018.csv"          # Celda 4
p_perm = MODEL_DIR / "features_permutation_importance_IDS2018.csv"  # Celda 4

feat_topk = json.loads(p_topk.read_text())
feat_cons = json.loads(p_cons.read_text())

df = pd.DataFrame({"feature": list(dict.fromkeys(feat_cons + feat_topk))})
df["in_consensus"] = df["feature"].isin(feat_cons).astype(int)
df["in_topk"]      = df["feature"].isin(feat_topk).astype(int)

# Merge con coeficientes Ridge/Lasso (abs)
if p_rl.exists():
    rl = pd.read_csv(p_rl)
    rl = rl.rename(columns={"ridge_abs_coef":"ridge_abs", "lasso_coef":"lasso"})
    df = df.merge(rl[["feature","ridge_abs","lasso","selected_by_lasso"]], on="feature", how="left")

# Merge con Stability
if p_stab.exists():
    stab = pd.read_csv(p_stab)
    df = df.merge(stab, on="feature", how="left")

# Merge con Permutation Importance
if p_perm.exists():
    pi = pd.read_csv(p_perm)
    df = df.merge(pi[["feature","perm_import_mean","perm_import_std"]], on="feature", how="left")

# Orden sugerido: consenso primero, luego importancia promedio
imp_proxy = np.nan_to_num(df["ridge_abs"], 0) + np.nan_to_num(df["lasso"].abs(), 0) + np.nan_to_num(df["perm_import_mean"], 0)
df["imp_proxy"] = imp_proxy
df = df.sort_values(["in_consensus","imp_proxy"], ascending=[False, False])

cols_show = ["feature","in_consensus","in_topk","ridge_abs","lasso","selected_by_lasso",
             "stability_freq","perm_import_mean","perm_import_std"]
display(df[cols_show].reset_index(drop=True).head(40))

# Guardados
out_csv = MODEL_DIR / "features_summary_table_IDS2018.csv"
out_md  = MODEL_DIR / "features_summary_table_IDS2018.md"
df[cols_show].to_csv(out_csv, index=False)

# pequeño markdown para pegar en el TFG
with open(out_md, "w") as f:
    f.write("| Feature | In Consenso | In TopK | Ridge | Lasso | Sel Lasso | Stability | PermImp |\n")
    f.write("|---|---:|---:|---:|---:|---:|---:|---:|\n")
    for _,r in df[cols_show].iterrows():
        f.write(f"| {r['feature']} | {int(r['in_consensus'])} | {int(r['in_topk'])} | "
                f"{(r['ridge_abs'] if pd.notna(r['ridge_abs']) else 0):.4g} | "
                f"{(abs(r['lasso']) if pd.notna(r['lasso']) else 0):.4g} | "
                f"{int(r['selected_by_lasso']) if pd.notna(r['selected_by_lasso']) else 0} | "
                f"{(r['stability_freq'] if pd.notna(r['stability_freq']) else 0):.2f} | "
                f"{(r['perm_import_mean'] if pd.notna(r['perm_import_mean']) else 0):.4g} |\n")

print("💾 Guardados:")
print(" -", out_csv)
print(" -", out_md, "(tabla Markdown para el informe)")

# ==========================================================
# CELDA 4 — Stability Selection + Permutation Importance + CONSENSO
# ==========================================================
import numpy as np, pandas as pd, json, gc, warnings
from pathlib import Path
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV, Lasso
from sklearn.inspection import permutation_importance
from sklearn.ensemble import HistGradientBoostingClassifier

# Requiere: X_train_filt, X_val_filt, y_train, y_val, FEATURES_FILT, FEATURES_FINAL, MODEL_DIR
for v in ["X_train_filt","X_val_filt","y_train","y_val","FEATURES_FILT","FEATURES_FINAL","MODEL_DIR"]:
    assert v in globals(), f"Falta {v}. Ejecuta Celda 1-3 primero."

SEED = 42
np.random.seed(SEED)

# ---------- 1) Preparar subset para Stability Selection ----------
N_STAB = 200_000  # tamaño de muestra para estabilidad (sube/baja según RAM/tiempo)
if X_train_filt.shape[0] > N_STAB:
    frac = N_STAB / X_train_filt.shape[0]
    print(f"✂️ Submuestreando para Stability Selection ~{N_STAB:,} ({frac:.2%})…")
    sss_base = StratifiedShuffleSplit(n_splits=1, test_size=1-frac, random_state=SEED)
    idx_tr, _ = next(sss_base.split(np.zeros((y_train.shape[0],1)), y_train))
    X_stab = X_train_filt[idx_tr].astype(np.float64, copy=False)
    y_stab = y_train[idx_tr]
else:
    X_stab = X_train_filt.astype(np.float64, copy=False)
    y_stab = y_train

# Estandarización para Lasso
scaler_stab = StandardScaler()
X_stab_std = scaler_stab.fit_transform(X_stab)

# ---------- 2) Alpha óptimo con LassoCV (una vez) ----------
warnings.filterwarnings("ignore", category=UserWarning)
lasso_cv = LassoCV(
    eps=1e-3, n_alphas=40, cv=3, max_iter=5000, n_jobs=-1, random_state=SEED
).fit(X_stab_std, y_stab.astype(np.float64))
alpha_opt = float(lasso_cv.alpha_)
print(f"🏁 Alpha óptimo para Stability Selection (LassoCV): {alpha_opt}")

# ---------- 3) Stability Selection (repetir Lasso en submuestras) ----------
REPEATS = 10         # nº de repeticiones
SUB_FRAC = 0.75      # fracción de datos en cada repetición
sel_counts = np.zeros(X_stab.shape[1], dtype=np.int32)

sss = StratifiedShuffleSplit(n_splits=REPEATS, test_size=1-SUB_FRAC, random_state=SEED)
for r, (idx_sub, _) in enumerate(sss.split(np.zeros((y_stab.shape[0],1)), y_stab), start=1):
    X_sub = X_stab[idx_sub]
    y_sub = y_stab[idx_sub]
    X_sub_std = scaler_stab.transform(X_sub)  # usar el scaler base para estabilidad
    lasso = Lasso(alpha=alpha_opt, max_iter=5000, random_state=SEED+r)
    lasso.fit(X_sub_std, y_sub.astype(np.float64))
    sel_counts += (np.abs(lasso.coef_) > 1e-8).astype(np.int32)
    if r % 2 == 0:
        print(f"   · Repetición {r}/{REPEATS} completada")

sel_freq = sel_counts / REPEATS
stab_df = pd.DataFrame({
    "feature": FEATURES_FILT,
    "stability_freq": sel_freq
}).sort_values("stability_freq", ascending=False)
stab_df.to_csv(MODEL_DIR / "features_stability_IDS2018.csv", index=False)
print("💾 Guardado stability table → features_stability_IDS2018.csv")

STAB_THR = 0.60  # umbral de estabilidad (≥60%)
stable_feats = stab_df.loc[stab_df["stability_freq"] >= STAB_THR, "feature"].tolist()
print(f"🧷 Features estables (≥{int(STAB_THR*100)}%): {len(stable_feats)}")

# ---------- 4) Permutation Importance (val) con modelo ligero ----------
# Construir X_val con las columnas filtradas de Celda 2 (FEATURES_FILT)
feat2idx = {f:i for i,f in enumerate(FEATURES_FILT)}

# Usaremos el consenso provisional (union de estables y finales) para el modelo
union_feats = list(dict.fromkeys(list(stable_feats) + list(FEATURES_FINAL)))
idx_union = [feat2idx[f] for f in union_feats if f in feat2idx]
X_val_union = X_val_filt[:, idx_union].astype(np.float64, copy=False)

# Submuestreo de val para no tardar demasiado en permutation
N_VAL_PI = min(150_000, X_val_union.shape[0])
if X_val_union.shape[0] > N_VAL_PI:
    # muestreo estratificado sobre y_val
    frac_val = N_VAL_PI / X_val_union.shape[0]
    sss_val = StratifiedShuffleSplit(n_splits=1, test_size=1-frac_val, random_state=SEED)
    idx_v, _ = next(sss_val.split(np.zeros((y_val.shape[0],1)), y_val))
    X_val_pi = X_val_union[idx_v]
    y_val_pi = y_val[idx_v]
else:
    X_val_pi = X_val_union
    y_val_pi = y_val

hgb = HistGradientBoostingClassifier(random_state=SEED)
hgb.fit(X_stab[:, idx_union], y_stab)  # entrenamos en el subset de train estabilidad
pi = permutation_importance(
    hgb, X_val_pi, y_val_pi, n_repeats=3, random_state=SEED, n_jobs=-1
)

pi_df = pd.DataFrame({
    "feature": union_feats,
    "perm_import_mean": pi.importances_mean,
    "perm_import_std":  pi.importances_std
}).sort_values("perm_import_mean", ascending=False)
pi_df.to_csv(MODEL_DIR / "features_permutation_importance_IDS2018.csv", index=False)
print("💾 Guardado permutation importance → features_permutation_importance_IDS2018.csv")

# ---------- 5) CONSENSO TOP_K ----------
TOP_K = 27  # mismo K que en Celda 3
# (a) intersección entre finales (Celda 3) y estables
consensus = [f for f in FEATURES_FINAL if f in stable_feats]

# (b) si faltan para TOP_K, rellenar con las mejores por permutation (que no estén ya)
if len(consensus) < TOP_K:
    for f in pi_df["feature"].tolist():
        if f not in consensus:
            consensus.append(f)
            if len(consensus) == TOP_K:
                break

print(f"🎯 CONSENSO TOP_K={TOP_K}: {len(consensus)} features")
print("   Top 10 consenso:", consensus[:10])

with open(MODEL_DIR / "features_final_consensus_IDS2018.json", "w") as f:
    json.dump(consensus, f, indent=2)

print("💾 Guardados en:", MODEL_DIR)
print("   - features_stability_IDS2018.csv")
print("   - features_permutation_importance_IDS2018.csv")
print("   - features_final_consensus_IDS2018.json")

gc.collect()

# ==========================================================
# CELDA 5 — Validación de sets de variables (ROC-AUC, PR-AUC, F1)
# ==========================================================
import json, gc, numpy as np, pandas as pd
from pathlib import Path
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, average_precision_score, precision_recall_curve, f1_score
from sklearn.model_selection import StratifiedShuffleSplit

# Requiere de celdas previas:
for v in ["X_train_filt","X_val_filt","y_train","y_val","FEATURES_FILT","MODEL_DIR"]:
    assert v in globals(), f"Falta {v} — ejecuta Celdas 1-4."

# Cargar features finales Top-K (Celda 3) y consenso (Celda 4)
# (si no existen en RAM, los leemos del disco)
if 'FEATURES_FINAL' not in globals():
    p = MODEL_DIR / "features_final_IDS2018.json"
    assert p.exists(), "No encuentro features_final_IDS2018.json"
    FEATURES_FINAL = json.loads(p.read_text())

try:
    if 'consensus' not in globals():
        p_cons = MODEL_DIR / "features_final_consensus_IDS2018.json"
        consensus = json.loads(p_cons.read_text())
except Exception:
    consensus = FEATURES_FINAL[:]  # fallback

# Mapeo nombre->índice sobre el espacio filtrado (Celda 2)
feat2idx = {f:i for i, f in enumerate(FEATURES_FILT)}
def cols_idx(names):
    missing = [f for f in names if f not in feat2idx]
    if missing:
        print(f"⚠️ Aviso: {len(missing)} features no están en FEATURES_FILT y se omiten:", missing[:8], "...")
    return [feat2idx[f] for f in names if f in feat2idx]

SETS = {
    "All_filtered": FEATURES_FILT,
    "TopK_Celda3": FEATURES_FINAL,
    "TopK_Consensus_Celda4": consensus,
}

# Muestreo opcional para el ajuste (para acelerar)
N_TRAIN_FIT = min(500_000, X_train_filt.shape[0])  # sube/baja si quieres
if X_train_filt.shape[0] > N_TRAIN_FIT:
    frac = N_TRAIN_FIT / X_train_filt.shape[0]
    print(f"✂️ Muestreo para ajuste ~{N_TRAIN_FIT:,} ({frac:.2%})…")
    sss = StratifiedShuffleSplit(n_splits=1, test_size=1-frac, random_state=42)
    idx_fit, _ = next(sss.split(np.zeros((y_train.shape[0],1)), y_train))
else:
    idx_fit = np.arange(X_train_filt.shape[0])

def eval_set(name, feat_names):
    idx = cols_idx(feat_names)
    Xtr = X_train_filt[idx_fit][:, idx].astype(np.float32, copy=False)
    ytr = y_train[idx_fit]
    Xva = X_val_filt[:, idx].astype(np.float32, copy=False)
    yva = y_val

    # Pipeline: z-score + LR (saga) con balanceo
    pipe = Pipeline([
        ("scaler", StandardScaler(with_mean=True, with_std=True)),
        ("lr", LogisticRegression(
            solver="saga",
            penalty="l2",
            C=1.0,
            class_weight="balanced",
            max_iter=400,
            n_jobs=-1,
            random_state=42
        ))
    ])
    pipe.fit(Xtr, ytr)
    # Probabilidades
    try:
        p = pipe.predict_proba(Xva)[:, 1]
    except Exception:
        # fallback si no hay predict_proba (no debería ocurrir con LR)
        p = pipe.decision_function(Xva)
        p = (p - p.min()) / (p.max() - p.min() + 1e-12)

    # Métricas
    roc = roc_auc_score(yva, p)
    ap  = average_precision_score(yva, p)

    # F1 en 0.5 y F1 máximo
    yhat_05 = (p >= 0.5).astype(int)
    f1_05   = f1_score(yva, yhat_05)

    pr_prec, pr_rec, pr_thr = precision_recall_curve(yva, p)
    # thresholds alínean con pares (prec, rec) excepto el último punto
    f1s = 2*pr_prec[:-1]*pr_rec[:-1] / (pr_prec[:-1] + pr_rec[:-1] + 1e-12)
    best_idx = int(np.nanargmax(f1s))
    f1_best  = float(f1s[best_idx])
    thr_best = float(pr_thr[best_idx])

    # Coefs absolutas ordenadas (para informe)
    lr = pipe.named_steps["lr"]
    coefs = np.abs(lr.coef_.ravel())
    order = np.argsort(-coefs)
    top_coef = [(feat_names[i], float(coefs[i])) for i in order[:min(20, len(order))]]

    return {
        "set": name,
        "n_features": len(idx),
        "roc_auc": roc,
        "pr_auc": ap,
        "f1@0.5": f1_05,
        "f1@best": f1_best,
        "thr_best": thr_best,
        "top_coef": top_coef,
        "coef_full": {feat_names[i]: float(coefs[i]) for i in range(len(idx))}
    }

results = []
for name, feats in SETS.items():
    print(f"\n🔎 Evaluando set: {name}  (n={len(feats)})")
    res = eval_set(name, feats)
    results.append(res)
    print(f"   ROC-AUC={res['roc_auc']:.4f} | PR-AUC={res['pr_auc']:.4f} | F1@0.5={res['f1@0.5']:.4f} | F1@best={res['f1@best']:.4f} (τ*={res['thr_best']:.3f})")
    print("   Top 5 por |coef|:", [t[0] for t in res["top_coef"][:5]])

# Tabla resumen
df_sum = pd.DataFrame([{
    "set": r["set"],
    "n_features": r["n_features"],
    "roc_auc": r["roc_auc"],
    "pr_auc": r["pr_auc"],
    "f1@0.5": r["f1@0.5"],
    "f1@best": r["f1@best"],
    "thr_best": r["thr_best"],
} for r in results]).sort_values("roc_auc", ascending=False)

print("\n✅ Validación comparativa terminada")
display(df_sum)

# Guardar artefactos
MODEL_DIR.mkdir(parents=True, exist_ok=True)
df_sum.to_csv(MODEL_DIR / "validation_feature_sets_IDS2018.csv", index=False)

# Guardar coeficientes por set (para informe)
for r in results:
    pd.Series(r["coef_full"]).to_csv(MODEL_DIR / f"coef_{r['set']}_LR_IDS2018.csv", header=["abs_coef"])

print("💾 Guardados en:", MODEL_DIR)
print("   - validation_feature_sets_IDS2018.csv")
print("   - coef_*_LR_IDS2018.csv")

gc.collect()

# ==========================================================
# CELDA 6 — Deltas (‰) + tabla detallada
# ==========================================================
import json, gc
import numpy as np, pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

if 'MODEL_DIR' not in globals():
    MODEL_DIR = Path("/content/drive/MyDrive/TFG/modelo_guardado_CIC2018")
VAL_SUM_CSV = MODEL_DIR / "validation_feature_sets_IDS2018.csv"
assert VAL_SUM_CSV.exists(), "Falta validation_feature_sets_IDS2018.csv (ejecuta Celda 5)."

df = pd.read_csv(VAL_SUM_CSV)

# Ordena por ROC-AUC y añade más decimales + deltas (per-mille)
df = df.sort_values('roc_auc', ascending=False).reset_index(drop=True)
for col in ['roc_auc','pr_auc','f1@0.5','f1@best','thr_best']:
    df[col] = df[col].astype(float)
best_roc = df['roc_auc'].max()
best_pr  = df['pr_auc'].max()
df['ΔROC (‰)'] = (df['roc_auc'] - best_roc) * 1000.0   # mejor = 0.0
df['ΔPR  (‰)'] = (df['pr_auc']  - best_pr)  * 1000.0

print("📊 Tabla (5 decimales):")
display(df[['set','n_features',
            'roc_auc','pr_auc','f1@0.5','f1@best','thr_best','ΔROC (‰)','ΔPR  (‰)']].style.format({
    'roc_auc': '{:.5f}', 'pr_auc': '{:.5f}', 'f1@0.5': '{:.5f}', 'f1@best': '{:.5f}',
    'thr_best': '{:.3f}', 'ΔROC (‰)': '{:.2f}', 'ΔPR  (‰)': '{:.2f}'
}))

# ---- Gráfico: delta ROC en ‰ (cuanto más cerca de 0, mejor)
plt.figure(figsize=(7.5, 4.2))
plt.title("ΔROC-AUC (en ‰) respecto al mejor set")
plt.bar(df['set'], df['ΔROC (‰)'])
plt.axhline(0, linestyle='--')
for i, v in enumerate(df['ΔROC (‰)']):
    plt.text(i, v, f"{v:.2f}", ha='center', va='bottom' if v>=0 else 'top', fontsize=9, rotation=0)
plt.xticks(rotation=20, ha='right')
plt.ylabel("Delta ROC-AUC (‰)")
plt.tight_layout()
plt.savefig(MODEL_DIR / "plot_delta_roc_per_mille_IDS2018.png", dpi=140)
plt.show()

# ---- Gráfico: delta PR-AUC en ‰
plt.figure(figsize=(7.5, 4.2))
plt.title("ΔPR-AUC (en ‰) respecto al mejor set")
plt.bar(df['set'], df['ΔPR  (‰)'])
plt.axhline(0, linestyle='--')
for i, v in enumerate(df['ΔPR  (‰)']):
    plt.text(i, v, f"{v:.2f}", ha='center', va='bottom' if v>=0 else 'top', fontsize=9, rotation=0)
plt.xticks(rotation=20, ha='right')
plt.ylabel("Delta PR-AUC (‰)")
plt.tight_layout()
plt.savefig(MODEL_DIR / "plot_delta_pr_per_mille_IDS2018.png", dpi=140)
plt.show()

print("🖼️ Guardado Δ-plots en:")
print(" -", MODEL_DIR / "plot_delta_roc_per_mille_IDS2018.png")
print(" -", MODEL_DIR / "plot_delta_pr_per_mille_IDS2018.png")
gc.collect()

# ==========================================================
# CELDA 7 — PR curves (zoom alta precisión) para los 3 sets
# ==========================================================
import numpy as np, pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_curve
import matplotlib.pyplot as plt

# Requiere objetos de Celdas 1–5
for v in ["X_train_filt","X_val_filt","y_train","y_val","FEATURES_FILT","MODEL_DIR"]:
    assert v in globals(), f"Falta {v}."

import json
SETS = {}
# cargamos listas
SETS["TopK_Consensus_Celda4"] = json.loads((MODEL_DIR / "features_final_consensus_IDS2018.json").read_text())
SETS["TopK_Celda3"]          = json.loads((MODEL_DIR / "features_final_IDS2018.json").read_text())
SETS["All_filtered"]         = list(FEATURES_FILT)

feat2idx = {f:i for i,f in enumerate(FEATURES_FILT)}

def idx_of(names): return [feat2idx[f] for f in names if f in feat2idx]

# Submuestreo para entrenar y para predecir (rápido)
N_TR = min(300_000, X_train_filt.shape[0])
N_VA = min(150_000, X_val_filt.shape[0])

sss_tr = StratifiedShuffleSplit(n_splits=1, test_size=1-N_TR/X_train_filt.shape[0], random_state=42)
idx_tr, _ = next(sss_tr.split(np.zeros((y_train.shape[0],1)), y_train))
sss_va = StratifiedShuffleSplit(n_splits=1, test_size=1-N_VA/X_val_filt.shape[0], random_state=42)
idx_va, _ = next(sss_va.split(np.zeros((y_val.shape[0],1)), y_val))

plt.figure(figsize=(7.2, 5.0))
plt.title("Curvas PR (zoom alta precisión) — IDS2018")
for name, feats in SETS.items():
    cols = idx_of(feats)
    Xtr = X_train_filt[idx_tr][:, cols]
    ytr = y_train[idx_tr]
    Xva = X_val_filt[idx_va][:, cols]
    yva = y_val[idx_va]

    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("lr", LogisticRegression(solver="saga", penalty="l2", C=1.0,
                                  class_weight="balanced", max_iter=400, n_jobs=-1, random_state=42))
    ]).fit(Xtr, ytr)

    p = pipe.predict_proba(Xva)[:, 1]
    prec, rec, _ = precision_recall_curve(yva, p)

    # filtrar a región de precisión alta
    mask = prec >= 0.95
    if mask.sum() < 2:  # si casi no hay puntos ≥0.95, relajar a 0.90
        mask = prec >= 0.90
    plt.plot(rec[mask], prec[mask], label=f"{name}")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.xlim(0, 1)
plt.ylim(0.90, 1.005)  # zoom
plt.legend()
plt.tight_layout()
out_path = MODEL_DIR / "plot_pr_zoom_high_precision_IDS2018.png"
plt.savefig(out_path, dpi=140)
plt.show()
print("🖼️ Guardado:", out_path)

# ==========================================================
# CELDA 8 — Lock de listas y versiones (reproducibilidad)
# ==========================================================
import json, platform, sklearn, numpy as np, pandas as pd, datetime as dt
from pathlib import Path

lock = {
    "timestamp": dt.datetime.utcnow().isoformat() + "Z",
    "features_topk": json.loads((MODEL_DIR/"features_final_IDS2018.json").read_text()),
    "features_consensus": json.loads((MODEL_DIR/"features_final_consensus_IDS2018.json").read_text()),
    "versions": {
        "python": platform.python_version(),
        "numpy": np.__version__,
        "pandas": pd.__version__,
        "sklearn": sklearn.__version__,
    }
}
with open(MODEL_DIR/"features_lock_IDS2018.json","w") as f:
    json.dump(lock, f, indent=2)
print("🔒 Lock guardado en:", MODEL_DIR/"features_lock_IDS2018.json")

# ==========================================================
# CELDA 9 — Helper: seleccionar columnas por lista (topk/consenso)
# ==========================================================
import json
from typing import Literal

def subset_by_list(df: pd.DataFrame, which: Literal["topk","consenso"]="consenso"):
    path = MODEL_DIR / ("features_final_IDS2018.json" if which=="topk"
                        else "features_final_consensus_IDS2018.json")
    names = json.loads(path.read_text())
    cols = [c for c in names if c in df.columns]
    missing = [c for c in names if c not in df.columns]
    if missing:
        print(f"⚠️ Aviso: {len(missing)} columnas no están en el DF:", missing[:8], "...")
    return df[cols].copy()

print("✅ Usa subset_by_list(df, 'topk'|'consenso') para crear tus matrices finales.")